### ISSUE TITLE
How to deal with the request？

### ISSUE THREAD

**Issue by Zhangyc0** [Vozec/AES-DFA#1]
I now have a right_ciphertext and two fault_ciphertexts. The injection attack occurred in the eighth round. I want to restore the 16 keys in the tenth round.

**Comment by Zhangyc0** [comment]
Such as, I have a cipher-text is 66e94bd4ef8a2c3b884cfa59ca342b2e, and  have two fault-cipher-value is fd776e5679bde2f51dc67925e3fd61c8 and 6d6b8f2ad4ba243deb3b4be24fe202cf.
If attacker injects the attack in the 8th round, and we need the 10th round keys, what should i do? :)

**Comment by Vozec** [comment]
You don't have enought pairs to attack your system. This implementation work for a fault in the 9th round.
For you'r case, take a look at: 
- https://github.com/arusson/dfa-aes which support fault in 8th round.

**Comment by Zhangyc0** [comment]
Thx for your suggestion
